spring:
  servlet:
    multipart:
      enabled: true # 开启文件上传
      max-file-size: 10MB # 限制文件上传大小为10M
minio:
  endpoint: http://127.0.0.1:9000 #MinIO服务所在地址
  bucketName: mall #存储桶名称
  accessKey: minioadmin #访问的key
  secretKey: minioadmin #访问的秘钥
